/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
              // Reading from System.in
          Scanner reader = new Scanner(System.in);  
        
          System.out.println("Enter side 1: ");
          // Scans the next token of the input as an int.
          int side_1 = reader.nextInt();
          
          System.out.println("Enter side 2: ");
          // Scans the next token of the input as an int.
          int side_2 = reader.nextInt();
          
          System.out.println("Enter side 3: ");
          // Scans the next token of the input as an int.
          int side_3 = reader.nextInt();
          
          if (isTriangle(side_1, side_2, side_3)) {
              System.out.println("This is a triangle.");
          }
          else {
              System.out.println("This is not a triangle.");
          }
          
          reader.close();
    }

    public static boolean isTriangle(double a, double b, double c) {
        if ((a + b > c) && (a + c > b) && (b + c > a)) 
            {// should be a + c > b 
            return true; 
        }
        return false;
    }
}
