/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {
    double[] tria1;
    double[] tria2;
    double[] tria3;
    double[] tria4;

    @BeforeEach void initEach(){
        tria1 = new double[3];
        tria2 = new double[3];
        tria3 = new double[3];
        tria4 = new double[3];
        tria1[0] = -10;
        tria2[0] = 0;
        tria3[0] = 1;
        tria4[0] = 2;
        tria1[1] = 10;
        tria2[1] = 1;
        tria3[1] = 1;
        tria4[1] = 2;
        tria1[2] = -1;
        tria2[2] = 0;
        tria3[2] = 10;
        tria4[2] = 2;
    }

    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void isTriangleTest() {
        assertEquals(false, App.isTriangle(-10,0,15),"Testing for triangle 1: ");
        assertEquals(false, App.isTriangle(0,0,0),"Testing for triangle 2: ");
        assertEquals(true, App.isTriangle(3,4,5),"Testing for triangle 3: ");
        assertEquals(true, App.isTriangle(4,4,4),"Testing for triangle 4: ");
    }
}
